@startuml
'https://plantuml.com/class-diagram

class ValidationUI{

}
class ValidationController{
-code
+ getDiagnosedTest()
+ validate(code)
}
class TestStore{
-code
+getDiagnosedTest()
+setValid(code)
}

ValidationUI ..> ValidationController
ValidationController ..> TestStore


@enduml