@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Laboratory Coordinator" as LC
 LC -> ":System" : Asks to validate a diagnosis
 activate LC
 activate ":System"
 ":System" --> LC :shows the unvalidated tests
 deactivate ":System"
 LC -> ":System" : Selects the desired Test
 activate ":System"
 ":System" --> LC : Shows Registation date, Chemical analysis date and Diagnosis date
 deactivate ":System"
 LC -> ":System" : Verifies the dates and validates the Test
 activate ":System"
 ":System" --> LC : saves the validation and the date of validation
 @enduml